### ISSUE TITLE
Xebra.js: State::close() method causes Max crash

### ISSUE THREAD

**Issue by JulesFrancoise** [Cycling74/miraweb#105]
Hello,

It seems that the `State::close()` method causes Max to crash (the log indicates a segmentation fault).

To reproduce with the `mira.channel` help patcher, type the following in the browser console:
`xebraState.close()`

**Comment by fde31** [comment]
yes. Reproducible for me here. Passing to @starakaj

**Comment by starakaj** [comment]
Okay, got it. This requires a fix to the miraweb package, but it should be okay now.

**Comment by starakaj** [comment]
Replace miraweb/extensions/mira_ws_server.mxo with this to test

[mira_ws_server.mxo.zip](https://github.com/Cycling74/miraweb/files/1294029/mira_ws_server.mxo.zip)

**Comment by benbrackenc74** [comment]
With this new mira_ws_server, Max is still crashing. report:
https://pastebin.com/TF715Jee

**Comment by benbrackenc74** [comment]
this is fixed. I was bitten by some search path baloney.
