### ISSUE TITLE
Umenu with single item does not display contents

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#110]
In the (admittedly strange) case where a umenu has only one item, MiraWeb does not seem to show that item.
Mira app does show the item.

<pre><code>
----------begin_max5_patcher----------
371.3ockRssiBBCD8Y3qfzmYMf5xp6uxlMlBLhUgVR6ThFi+6auPUHqYuPBL
LW5YldNy03HRo3LnHIum7QRTz03nHWHafnQ+HRG8bUKU4Jin6.tlj5yLPkbZ
G78D8Tr5.i2rSBUnG970aWjkljmW3LYYVyxkKxR9b7PrZGPhxiurL.DW2IzX
Kfttu5N7RSaQPtC3zxV2.jGPAgN0z.J7huBR.TOh3kdvOZDFGIo17l26iio0
Ldny2AiN.06nHJYkZDd7mZjyFIMK2zpAw9P3P7oCeqf27T9aVUpCBI96kEtN
qdRNFefoXAhxm+Vb7Ci66s3z+3RPGSRWr2h9OH3aysJbwFmN+pQ0sOEFoeyT
QuWBJfiTjI3yjwGKC4OeYH6IH7uaeIs5TiTn40yZdCWXPpkUcZZ3YaDYS3MG
bDZe+.HUiWDGwYnsiBo08sTmKi6ccpDQBVcwW+ZWDpzPin4Rnkd89bwZh+nh
ZPx0rQIzz4aweEZFoG.
-----------end_max5_patcher-----------
</code></pre>

**Comment by fde31** [comment]
Can reproduce _but_ the single item has to be a number. If you use `a` instead it works fine. Shouldn't be that hard to fix.

**Comment by benbrackenc74** [comment]
I removed the check for item length, and just now check for items or <empty> to return null. @fde31 want to double check and close out?

**Comment by fde31** [comment]
labelling as fixed.
