### ISSUE TITLE
comment objects prevent interaction

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#12]
Reported by Pedro Louzeiro on the forums:

"Is it normal that the comments are opaque to the touch? I can’t click on a button if it’s underneath a comment"

Basically you can't interact with any object placed under a comment in MiraWeb while you can in Max.

**Comment by fde31** [comment]
This is a more general issue as in Max 'ignoreclick' passes the the interaction down to any elements underneath. Same in Mira App.

**Comment by fde31** [comment]
Two rather shortish commits in order to allow dynamic toggling of the interaction enabled/disabled state on a PixiUiObject. Additionally hooked it up properly to the ignoreclick attribute.

Wanna take a look @starakaj ?

**Comment by starakaj** [comment]
Cool, these changes make sense to me. It does make it impossible for an object to have a hit area that is different from it's bounds, but that's not a problem for any of the objects we support.
