### ISSUE TITLE
live.grid doesn't support 'highlight' indication

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#13]
Reported on the forums by WETTERBERG:

> Hey gang, and merry christmas. I just wanted to drop in and say wow, as well. I’m so happy I bought these multitouch displays a while back, this is going to be so much fun! I’m so thankful for this, it’s going to really make a difference. I CAN RUN SO MANY SEQUENCERS NAO!
> 
> I just stumbled upon a small display bug here; the "highlight" of live.grid doesn’t work. I took a quick screen shot to show you what I mean.
> 
> Max in the background, google chrome in the foreground. Same results with Safari.
> http://i.imgur.com/k9iUxbP.png

I can totally reproduce this issue with MiraWeb while I verified that the highlighting is shown in Mira App.

**Comment by benbrackenc74** [comment]
'currentstep' should provide this, I can take a look.

**Comment by benbrackenc74** [comment]
Hm, actually, 'currentstep' doesn't seem valid, it just shows up as 'undefined' when I add it to the live.grid.js, maybe @starakaj wants to take a look?

**Comment by benbrackenc74** [comment]
Actually, it looks like 'currentstep' needs to be added over in xebra.js/src/lib/objectList.js:
https://github.com/Cycling74/xebra.js/blob/dev/src/lib/objectList.js#L163

This seems a little cumbersome to have to add it multiple places like this.

**Comment by fde31** [comment]
hmmm yeah I agree. We made the decision to move the default parameter list into xebra.js in order to simplify the process for users of the lib, so that there is no need to declare all params yourself for supported_objects. 

There is this issue: https://github.com/Cycling74/xebra.js/issues/1

which adds support for custom object with parameter list declaration. Maybe MiraWeb should use this instead to avoid this double dance?

Would like to get some input from @starakaj if that xebra.js change is supported in the backend already as certain non-ui objects weren't receiving proper updates due to their 'nobox' format.

**Comment by starakaj** [comment]
Hey, sorry for being so quiet here. Yes, that change is supported in the backend, so it should be possible to add parameters to miraweb supported objects that are not listed in the xebra.js object list.

Agreed that it's a bit annoying to have to change this in multiple places. We could simply have miraweb automatically add any needed extra parameters to its supported_objects list. But probably we want to avoid a situation where the "implicit" object parameter list that miraweb supports starts to diverge too much. Then again, we definitely want people to be able to contribute to miraweb without having to mess around with xebra.js, right?

What's the best way to address this? I feel like we should let miraweb add new parameters automatically, but also have some way of making sure that xebra.js and miraweb stay in sync. Maybe some kind of script we can run?

**Comment by benbrackenc74** [comment]
This should be in the next miraweb/mira package. I'm sidestepping the deeper issue for now, though I can expect it will come up fairly often.
