### ISSUE TITLE
xebra.js/examples/06-p5js missing support files

### ISSUE THREAD

**Issue by aumhaa** [Cycling74/miraweb#130]
Seems like some files are missing from the package, I get:

Not allowed to load local resource: file:///Users/amounra/GitHub/miraweb/packages/xebra.js/examples/js/lib/boid.js

Did a search and nothing comes up, so I'm guessing some local files didn't get added to the package.

**Comment by starakaj** [comment]
Okay, I see. Looks like that file didn't get included somehow when we merged xebra.js into miraweb. Thanks for pointing this out!

**Comment by starakaj** [comment]
Somehow this never got resolved, and now I can't find this local file either...

**Comment by catarak** [comment]
since i made this example, i can fix this!
