### ISSUE TITLE
Display different mira tabs as independent browser tabs.

### ISSUE THREAD

**Issue by AdrianArtacho** [Cycling74/miraweb#132]
I am using miraweb to coordinate a choreography (around 20 people) based on visual cues they get on their smartphones' browser. Before the performance, each person will be assigned a role, and thus it would be ideal to forward each user to a specific URL where only the tab that is relevant to them can be seen full-screen.

Can this be done?
Any advice would be much appreciated ;)

**Comment by fde31** [comment]
That sounds awesome. 

Unfortunately with the current way MiraWeb is designed this is not really possible I'm afraid. For more granular control we'd advise taking a look at xebra.js and / or the new Node For Max package to build more custom experiences for your use-case or forking the MiraWeb client by itself.
