### ISSUE TITLE
Enable/disable a mira.frame object via attribute

### ISSUE THREAD

**Issue by starakaj** [Cycling74/miraweb#134]
Would be cool if it were possible to enable/disable a mira.frame object using an attribute. When a mira.frame object is disabled, it does not appear in the mira context, and will not be mirrored to any devices.

**Comment by 1offby** [comment]
Maybe merge #124 with this I think its the same FR.

**Comment by starakaj** [comment]
I think.......... you are right. This is the same thing. Thanks!

**Comment by starakaj** [comment]
Duplicate of #124
