### ISSUE TITLE
Unlock aspect ratio

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#14]
Currently mira.frame has a fixed aspect ratio, which might be helpful to unlock in order to optimise. patches for certain devices. If this happens this work needs to be done on the Max site. Ticketing here for documentation purposes and in order to avoid duplicate FR and reports.

**Comment by benbrackenc74** [comment]
I believe this is all set and will be in the next update.

**Comment by AdrianArtacho** [comment]
Is it possible to show up each mira.frame in a single-tab browser window, rather than as multiple tabs in a single window? any workarounds?

**Comment by starakaj** [comment]
Hi Adrian, no, that's not currently possible. You could always open up multiple browser tabs, connect each one to the same instance of Max, and then manually switch each one over to a different Mira tab, but that doesn't sound very fun. What exactly are you trying to do, that you'd prefer browser tabs over Mira tabs?

Also, as this doesn't really relate to the original issue, would you mind creating a new issue, so we can have this discussion there?

**Comment by AdrianArtacho** [comment]
Thanks for your advice, Sam.

I've open a a [new issue](https://github.com/Cycling74/miraweb/issues/132) for this question.
