### ISSUE TITLE
mira.multitouch ignores 'Draw Touches on Device' (remote_circles)

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#15]
Toggling the 'Draw Touches on Device' attr doesn't have any effect and mira.multitouch keeps drawing the touch circles regardless of the current setting

**Comment by fde31** [comment]
I added support for the `remote_circles` and `remote_gestures` attributes to show & hide gestures and touch points accordingly. Might be nice to get someone to double check/test on a mobile/touch device additional to my testing so far.

**Comment by catarak** [comment]
tested and looked over the code, all looks good to me 😄

**Comment by fde31** [comment]
sweet! thx
