### ISSUE TITLE
live.tab: ignores text color attributes

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#151]
The text color of live.tab is always set by the bordercolor:

<pre><code>
----------begin_max5_patcher----------
600.3ociTssiaBCD8Y3q.4moHayM69qTUEYHlDuKwNxXnY0p7uWeARfFV0MR
gId7vLyYlyIeFGAZT23Cfjel7qjnnOiih7tbNhlOGAtvt01yF7gA5ES7LCqA
jFtbhokrK7cuyvuYTxVUuRGJALClZefJnPDsBVSJxQ40NWUU35hRHk.yoXTU
ZBJCl7647nFM8bi4iq7PZ.fzv2tdEy.dDmb7xgdgjOb3JyzdVHO4hGspa1zK
zJx5p5ZC5ytBWVPctvy8ToO5xsc1RcNn4slPdwd7Qo00HDhfpJPoIEPblMcT
RcMEaKqKM3RXlyfyf1OnRbIolPgU38filOvkFlQnjtp.miPHYsF6P2On651h
tWgR9q.9EWqQm3nespZd6G4K6zFk9HW++pjeMagZABUWUTCKIj+I2VvIj1s5
v5UzF7rk3T8H+NpCxSiVShvk65Z6xRaYpFt9.WxZ54qqrscBrLe+jO6cfMwO
dfYLZQyng+7WCyJjYIhSFzOxUcKtW7utn8J4ouRprIvgyJs4aEI211yRBkj6
TDl+n7lyZt+bmZT6s1r3rChadCehKeHb1jyEYFdm6FkByf4ivnCFt+db7Si+
483zu4elbQnYYctrC9ZAEB4nS44XmAWQxpspKZNgfJPTjSdYMYPmSHonnFWU
tRD0vZe+jVMJOtgncRprUnWz99F2OI7HvdDU3tzE3Jn6KLfc85DWOLKW8X2h
72BzYRp+nPFN5yIPymDKw6G8.l1NIL1wvnNvDtUU.BupxJAkiBeqG6l21R5m
pNVyvUVa3EbC+36w+Evuo+FM
-----------end_max5_patcher-----------
</code></pre>

All other text colors are ignored.

**Comment by starakaj** [comment]
It's just a question if actually using the text color attributes, instead of totally ignoring them.

**Comment by starakaj** [comment]
Ready to test.
