### ISSUE TITLE
slider ignores opacity value for 'On Color' (knobcolor)

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#16]
Changing the knobcolor opacity doesn't affect the rendering of the slider in MiraWeb. In contrast changing the opacity of the bgcolor and elementcolor attrs leads to the respected results

**Comment by benbrackenc74** [comment]
Seems like on line 46 in slider.js there is some hard coding of the knobcolor's alpha for some reason:
https://github.com/Cycling74/miraweb/blob/dev/src/js/objects/slider.js#L46-L51

 I see no reason why this is here. I'll do some double checking and implement.

**Comment by benbrackenc74** [comment]
fixed in  7c549c1
