### ISSUE TITLE
mira.frame ignores the color attribute

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#17]
Changing the value of the color attribute doesn't affect the color of the frame in MiraWeb

**Comment by fde31** [comment]
I checked in an enhancement to make the color attribute of mira.frame set the bg of our Pixi Canvas and the surrounding background. Additionally the bg of the frame tabs is coloured accordingly, too.

I used a feature branch though as we don't take the bg color of the containing patcher into consideration and per default mira.frame has a opacity applied that isn't 1. Therefore the color in the browser appears different than the one in Max. Maybe no issue as this replicates the behaviour of Mira App? However, guess we might wanna discuss/vote and decide whether this is 'good enough' for now or if we should also tackle the more complex patcher bg color mixing into consideration for a potentially to be released 'fix'.

**Comment by fde31** [comment]
Example of new background color usage:

<img width="1382" alt="screen shot 2017-01-04 at 19 31 49" src="https://cloud.githubusercontent.com/assets/1119173/21654161/a22c982e-d2b4-11e6-9a20-a3d1d4170e22.png">

Showcasing difference in color value due to opacity/mixing with patcher bg

<img width="1377" alt="screen shot 2017-01-04 at 19 32 12" src="https://cloud.githubusercontent.com/assets/1119173/21654160/a226b5c6-d2b4-11e6-98ce-59d870a5840c.png">

**Comment by wetterberg** [comment]
This now works in Max itself - is it also supposed to carry over into the browser? Essentially colouring the background? This does not happen currently.

**Comment by fde31** [comment]
It should be working as we were testing successfully. But the test setup is a bit more complex as this required a change in xebra.js

In general the best way to test all this and do dev work is by doing the following (<branch> to be replaced by the branch PR etc to test with)

1. Clone xebra-communicator repo and checkout <branch>
2. Clone xebra.js repo and checkout dev <branch>
3. Clone miraweb repo and checkout dev <branch>
4. npm link xebra-communicator into xebra.js
5. npm link xebra.js into miraweb

Guess we should consider revisiting this or providing some helper scripts to do all this work but that's the workflow for now. Sorry if it's a bit clumsy.

**Comment by benbrackenc74** [comment]
Closing this issue, and we can revisit the dev setup on another ticket
