### ISSUE TITLE
<object>: Panel

### ISSUE THREAD

**Issue by JCurtisRMIT** [Cycling74/miraweb#183]
**Describe the bug**
Sending `bgfillcolor` as a message to `panel` does not update the colour of the `panel` object 
But, using the inspector to change the same attribute actually does refresh the panel object to the selected colour

**Expected behavior**
Both using the inspector and sending the `bgfillcolor` message to the panel object will alter the panel's background color

**To Reproduce**
Send `bgfillcolor 1 0 0 1` to `panel` object inside `mira.frame` 
Observe change reflected in patch but not in Miraweb clients

**Screenshots**
![[Video Demonstration of behaviour](http://user-images.githubusercontent.com/25715542/103277080-4c9f9a80-4a1c-11eb-8757-51b187ff1db8.mp4)](http://user-images.githubusercontent.com/25715542/103277080-4c9f9a80-4a1c-11eb-8757-51b187ff1db8.mp4)

**Additional context**
Panel is really useful for making custom UIs for miraweb

**Desktop (please complete the following information):**
 - Operation System: MacOS Mojave, Chrome
 - Max Version:  {
	"version" : "Version 8.1.8 (28fa7f9) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.14.6 (Build 18G6032) x86_64",
	"samplerate" : 48000,
	"iovs" : 1024,
	"sigvs" : 512,
	"scheduler_in_audio_interrupt" : "on",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"eventinterval" : 30,
	"schedinterval" : 1.0,
	"overdrive" : "on",
	"pollthrottle" : 100,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 10.0,
	"schedslop" : 100.0,
	"eventprobing" : 0,
	"mixerparallel" : "on",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "qt",
	"glengine" : "gl3",
	"packages" : 	{
		"BEAP" : "1.0.3",
		"cv.jit" : "1.8.0",
		"gl3" : "0.1.3",
		"hap" : "1.0.6",
		"jit.mo" : "1.1.2",
		"max-mxj" : "7.2.5",
		"maxforlive-elements" : "0.3.7",
		"Mira" : "1.2.1",
		"Miraweb" : "1.2.5",
		"Node For Max" : "1.3.3",
		"RNBO" : "0.7.0",
		"Sadam Library" : "20.3.7",
		"Syphon" : "1.0.3",
		"VIDDLL" : "1.2.4",
		"Video & Graphics" : "7.2.0",
		"Vizzie" : "2.1.4",
		"zsa.descriptors" : "1.2.0"
	}

}

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: iOS 13.7
 - Browser Safari

**Comment by lysdexic-audio** [comment]
Via the c74 forum: `bgcolor` rather than `bgfillcolor` with list of rgba values will reflect changes in both the `panel` object in patch and in mira clients

**Comment by JCurtisRMIT** [comment]
Via the c74 forum: `bgcolor` rather than `bgfillcolor` with list of rgba values will reflect changes in both the `panel` object in patch and in mira clients
