### ISSUE TITLE
Windows can not find 'http://none:-1/?port=-1' Error

### ISSUE THREAD

**Issue by siavashkaveh** [Cycling74/miraweb#215]
**Describe the bug**
I receive the wrong name typed error when I want to open the browser in the Miraweb 

**Expected behavior**

I expect not to get errors and could open the browser.

**To Reproduce**

Open Miraweb help and click on the open web browser button. 
* ...

**Screenshots**

![Screenshot 2023-01-13 140538](https://user-images.githubusercontent.com/33105066/212398967-b24edb1f-e462-4f47-80d4-baf38db9246f.png)

**Comment by calcit3** [comment]
I have exact same problem.

I get this message when trying to use the Miraweb.

"websocket connection available at: http://none/:-1"

I Installed:

1. Java 8.0.3610.9

2. Bonjour Print Services for Windows v2.0.2

3. xebra.js as npm for Node.js (don't know how it works ,but as I understand I need it)

Max 8, Windows 10.

How to fix it?

**Comment by jinpavg** [comment]
Hi @siavashkaveh and @calcit3 thank you for logging this issue here-- for now, the workaround is to downgrade to Miraweb 1.2.5 on the package manager. This issue is being tracked over on #211
