### ISSUE TITLE
Miraweb should handoff between M4L and the Max Editor

### ISSUE THREAD

**Issue by starakaj** [Cycling74/miraweb#26]
Just like udpreceive does it.

**Comment by starakaj** [comment]
Alright so, you'll need to pull xebra-communicator/dev and rebuild miraweb to test this. You'll also need to rebuild the miraweb and mira packages. But I _think_ I've covered all the use cases. It's a bit slow sometimes, but at least things seem to be working.

**Comment by fde31** [comment]
Oki. I tested a couple of scenarios:

**/ Port Discovery**

Started Max and MiraWeb in different scenarios to see if port discovery works:

- [x] Port 8086 in use -> MiraWeb binds to Port 8087
- [x] Ports 8086 to 8089 in use -> MiraWeb binds to Port 8090

Given that iterative Port discovery when start MiraWeb seems to work fine and the correct address/port was reported on the Max console

**/ M4L and Max Handoff**

Running a fresh build of Mira, MiraWeb (incl. dev build of xebra-communicator/xebra.js)

1. Started Live
2. Use Device incl. Mira.frame -> M4L binds to Port 8086
3. Switch to Editor mode -> Max Editor binds to 8086 (with a bit of a delay)
4. Change State of Patch and Save (simple Toggle) via MiraWeb
5. Close Editor and therefore head back to Live
6. M4L is on Port 8086 again with updated Patch State and MiraWeb is in sync

Nice!

However I noticed a few things, maybe ok for now:

1. Having multiple devices in Live using mira.frame -> you only get one once you switch to the Editor. However, once fully back in Live all frames/tabs get restored.
2. Using a classic `loadbang` to display the hostname and port in a device works fine. However, when switching back and forth u may get a `http://none:-1` as the loadbang might hit mira.status too early before the server takeover was finished. Banging the output again works fine.

Overall I'm happy with the fix. Just wondering if we should do something about the latter issue. Maybe we should output something that MiraWeb is still setting up? Or should MiraWeb register the `bang` and output once it's done setting up?

Any thoughts @starakaj ?

**Comment by starakaj** [comment]
Hey, sorry for being mum on this for so long. To @fde31 's first point, I'm not sure how to handle that simply and cleanly. We could think about extending the miraweb protocol somehow, so that the server running in the Max process and in the Live process are able to forward packets between each other, but I'm not sure how easy it would be to do.

As for the second point, I made a modification in mira.status in 402e2c9d86e30297f80e0a6adbc2e26ca787bd38 that should address this.
