### ISSUE TITLE
live.grid: sluggish UI interaction in client

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#28]
Interacting with live.grid is very slow on the browser side. Paste the below in Max and open a browser and mouse in the browser window:

<pre><code>
----------begin_max5_patcher----------
737.3ocsU0ziaCBD8bxuhHeN0BveRO1KqTO1CUpppJh3PbXWLDgwY2sq1+6c
3C6jTksZSUVKYaXfAdy6MC7x7YIq0Ow6SV74E+bwrYuLe1LuImgYw9yR5XO0
HY89okHEG3osFwljkgQOvLJVG+xCpF5zCVI25ctLZcOy1rSnZWY3M1vlmmkV
hfmxkKvHRJZ4hLDx8CW.+V7qnmgEy97ddvsjjkW3cZ5.PbvRu99OgSl1bC.W
K2rhqXqk9EBeDtB0HZIQi8rC7MqXVqQrdvxO1pORSQdxQExAtd6n4Q6mtmRs
p8MoqylY+Nsw99l5HejcgwDpChdwXbFF+04yO9y+804Kem5emvvR25V8Kqwn
2ViwzTBHwXxxEjxTpStofNmWmVQoz5ZvbdUJsJmRwWTByF2x0rlGZM5A0lSU
OQqRC6lTz7vaJpnSBY+djv1u+.2zKzJeT6hYHhuWabcqV56JTgtdBNwvcTZX
99jjDlAhUKDnClfb8TcYRvU8FtQMHhrOvyvV1aeV92UcSJ8WYc5N1pch1cR3
0B4dZCS0F46jM7srAo8bIh0zvU1FsLfSfqc0NnzB2GWUjqFJD5gUARP.G7.w
uqwEuCVYwHOcZRwD7T7GAs3KPh9XI06DQnzLbUYdkCQkE4TDw0h5Lg+..nQ+
n5pQ3QbUTQf1tVYePH7NCme8HLnpYtGWKbYcIo51Ctuw2b0PqpNOCm6QUdAh
V6S8HYED5sGe+fKk5GuZHVSJv9DvpZbM1CvBZQdQDfwCL1pAjI9c7JFLwMID
p9VE.Ccq4l6zx+CFFxDc2PBY.TBtvGIXDlVdSSO2yTb42EZ3Hy+E9V2tUHkS
36z6AGuOJILZ7VojyOLXp.CvOpxmsj6Rl8GYQFEinW3Q2xmpPyg4lWDbCxxx
NSCitQFciPczjubFxLQ4gVmvbitAGzF3KRkqXKZcuQuGtMNdlO3JcZ9CVcqg
sQ.b8z8KS2rdMJAnduN+Ozrk0vJ
-----------end_max5_patcher-----------
</code></pre>

There are a ton of mgraphics.fill() and mgraphics.stroke() calls in for loops that are likely the culprits.

**Comment by fde31** [comment]
@catarak just to double check, all we need to do here is merge the pr in xebra.js? Or is any further work necessary?

**Comment by benbrackenc74** [comment]
this is working quite well here now, @fde31 do you want to take a look and merge the PR? https://github.com/Cycling74/miraweb/pull/71

**Comment by fde31** [comment]
yes. will do

**Comment by fde31** [comment]
commented on PR #71 but in general fine with merging at this point once @catarak feels like it given the review.
