### ISSUE TITLE
Multislider scaling off

### ISSUE THREAD

**Issue by catarak** [Cycling74/miraweb#31]
As reported by Andreas Wetterberg:

Scaling seems off? enable thin line and measure it out, the top end of the values clips out… A 0–16 multislider behaves and reads out like 0–15… I think it’s the placement of thin line that’s off on one of the views. mentally preparing for it being hard to explain… It’s particularly noticeable when using it as a position marker, which you need for live.grid, see above ;)

**Comment by wetterberg** [comment]
Tested, this appears fixed :) cheers
