### ISSUE TITLE
live.text partially ignores its @mode attribute

### ISSUE THREAD

**Issue by wetterberg** [Cycling74/miraweb#35]
it remains stuck in the "toggle" setting visually, even though its output is the "button" mode.

**Comment by fde31** [comment]
additional input from @1offby 

> Max 7.3.2 beta 6bf7de6 x64
> Mira v 1.2.0
> Miraweb v 1.1.0
> mac OS 10.12.3
> iOS 10.2.1
> 
> Live.text in button mode is displayed as rectangle in miraweb. Should be round. Mira app shows live.text as round in button mode.
> 
> 
> ----------begin_max5_patcher----------
> 216.3ocWOErqBCBD7L7UP3bsg1mVMuekWLFJkWEsEZ1BllX7eW1s1KxgMYFl
> Y2YdxYx1vhcVJ9U7mfwdxYLhBIXevL4ndwLnmIYxQGnK+GziVYw52tde.rlA
> m4Npn5CsOM57C1HYSsosiVRn81t5M+sZy8dHj7ceYOjhe6eRGMWc99K4CFWi
> c09RUgnRgy5CMkJ70jYNUWpDmQeu3bbHNm2hTOM8vBytfmZI1wbCuE.Ddrff
> N+J7GBB1GtM80DiFxoHliPBrTgVZ1KWsF5rfO4npvwK+h+FJcVk4
> -----------end_max5_patcher-----------

**Comment by benbrackenc74** [comment]
added @mode attribute with rev 770a840 on bb_livetext_buttonmode branch. Requires xebra.js bb_livetext_buttonmode_export branch as well.

**Comment by benbrackenc74** [comment]
and merged to dev branch.
