### ISSUE TITLE
multislider: skips over sliders when dragging quickly

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#38]
On the Max side, when you drag across multislider, all of the values are filled in. When you are on the Miraweb side, it will miss any number of sliders as you drag across. See patcher:

<pre><code>
----------begin_max5_patcher----------
726.3ockUssbaBCD8Y6uBFd1kQWAQ+G5WPlLYDXEGkfkbEBWmlI+6ck.Yvdr
Sa8LFIVsmU6d1K7w5U4M1Sp97rum8P1pUerd0pnnffUSuuJeu7TamrOpVdqc
+dkwmuY7Lu5jOJeqStK6mC5125dOS15r88Y6G5759N8VkKSaxZr9Wx7unxZb
1e0CxjlsA4+PdJYtNsQ0ZGLQaRlDdP5aeQa18jS05G8ULpp.sICWwhKBQXgR
KPYONAxLrWa5T9nWimDp2F8UayqeilOqncvmzDMIs2+dmJpbdPvmqWGdr4ej
jVD3oq4nzYj6U263VfKzvCU0X.hJDUBFEuA1QfUZUXGlwQ0BHfWDnmQRRHSZ
AHQzZBIrixKEkzKQ1CwbJLwWaMQxZHREiG8CFqBwqC63HbcI9N9AMgjTGTKh
DiqJ4gcUPjPJuD4MxubdQc3GnIASiIWTcLUyJWhTIeq01YcoqjUKfPdyM2g+
aUGGjNHC4UtmTFYyc3E14qBnVbL5JgnDE4aDPPhqxOKp4v7T5dL4egqSAhgG
4HfqXUQFmRpYXxk1qY2BX3Hmr7wb1U+6XDTxtYgNYtH.nBn58b99JyL2HbMU
vSP3gJUVvgEyEKgZV5cJQJSHqngeQpixgfMVhHDDJ+RjiNt+8CpQjfy.+mcR
4Q01mjduS2L3Uy65mZRm5RCsgcCJ6yIwI4KS9cVytunU8Bc6ew57mUtSeTU3
kMOfe7VJmbe5MNSaNp60ohtwyiCcRK+uSfzNYwyAqmRaGbpdXvszqslkSRGm
fFeRf4nrZRXpCAwKPgNP7W0lRJKDBDAG5tHw9SJWTPn07vrFBmUTJ30DwrMV
3DKautneDciNmTTzHaeamC9Bw1qfeiY35cFK3qcv2jNypSzXzgxkGNbT45m7
kHOBr3qiMWUahupMiuFSZ4NUHMMperCJW5.RwCLxfarH3jnLeDpEJZLC5o6F
t4OW+G.OJ.Ls
-----------end_max5_patcher-----------
</code></pre>

**Comment by fde31** [comment]
Interesting... I looked at the code to see if we are throttling somewhere but couldn't find any insight. Just to double check: @starakaj am I correct?

Guess the correct way to resolve that is by not really relying on the slider attribute value passed to the event handler and instead registering/deregistering pointers on multitouch and making use of the delta params on the event in order to draw a sort of path of values.

**Comment by starakaj** [comment]
Yeah @fde31 you have it right. If you look at live.grid, that's exactly what we're doing thqere, so it's just a question of adding similar code here.

**Comment by fde31** [comment]
I'll take a quick step at it. thx

**Comment by fde31** [comment]
assigned to @benbrackenc74 to review

**Comment by benbrackenc74** [comment]
This is working great!
