### ISSUE TITLE
investigate single repo/project setup

### ISSUE THREAD

**Issue by fde31** [Cycling74/miraweb#43]
It's currently a bit heavy to deal with the three repo setup wrt Pull Requests, Ticketing and especially testing. Seems like people more involved can deal with that easily using proper local linking etc. Ideally we'd consider moving to a more monolithic structure, which allows easier testing etc in a single repo while still publishing 2 (or maybe even just one) npm packages (xebra-communicator, xebra.js)  and MiraWeb as a Max package.

Other people have been dealing with similar issues. As an example reference:

https://github.com/babel/babel/blob/master/doc/design/monorepo.md

Their solution seems to be https://github.com/lerna/lerna which might be worth looking into instead of rolling our own scripted approach.

**Comment by starakaj** [comment]
+1 for this. Seems like it would make our lives much easier as well.

**Comment by fde31** [comment]
Ok. I updated the fde/monorepo branch and made the whole setup and usage process much more streamlined. Would u mind giving that branch a whirl @benbrackenc74 and @starakaj ? I don't wanna say too much and see if you guys can tackle along based on the README contents.

Guess once that's settled we should tackle the publishing and docs hosting workflow @benbrackenc74 but maybe it's better to do that in a sort of pair programming session so that both of us are aware and comfortable with the workflow?!

**Comment by starakaj** [comment]
Cool, I'm spinning it up now!

**Comment by fde31** [comment]
made some changes to the dev setup by updating to webpack > v2.0.0 and utilizing webpack-dev-server. Please refer to the README script section for the new dev build vs serve scripts. Also note that a dev-server does auto reload on detected changes and auto connects to Max for a smoother experience

**Comment by starakaj** [comment]
Auto reload and auto connect --- work great for me and big quality-of-life improvements!

**Comment by fde31** [comment]
Note: `publish`doesn't add a git tag in case MW got updated. It probably shoudl

**Comment by fde31** [comment]
we might also wanna consider checking if the current working dir is clean (in a git sense) b4 running `publish` in case of an error we could then safely roll back all changes

**Comment by benbrackenc74** [comment]
closing this out.
