### ISSUE TITLE
slider: accommodate relative attribute

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#45]
with @relative set to 1, sliders in Max will adjust the current value of a slider from where the mousedown occurs, and move up or down accordingly, and this is not reflected in miraweb. For an example:

<pre><code>
----------begin_max5_patcher----------
464.3ocwUsraBCCD7bxWQjOSQ4ATB7qfPHmvB0TGajsSDUU8eu9QL0HQPokJ
wkX10qmryrSLeFGgp3mAIJYUx5jnnOiihroLIh5iiPM3y0TrzVFpl2z.LEZh
aOEbVYyiqjbZqBV42g01vaUTPYOWZeVo5CJXOfutSBPpADqHb1VATqbcSdwx
ooSRxxKLKo8OR17C5DlG7LOTXU8aD1gPXbmOKelYYtEy7PfH6rcCu53KkHSp
uhiMOl7f5g.nZJ0860iwxrkogDq3dDawegXRJYGH7cUGVvvMPvNqy1bapkMH
0bEo93D3n.BcoaGvEjsbgikyeLWPYnXk6BlMfZkewYhEZJq.wVfgqbb4B4vc
vtsXkRPpzt9e9krWR60TixQaA9deZe9P3ob1gAU2qpT9FWnFWodYt3F6QXcD
IwSI29V6ge4e1q7OZTF6HOa17wOxy7uX+WsWC9yyFLVOvy1.zPD3o6Mne+q6
HGXb8LhRpeOTFuZnlN7Pcg6+DRKsyz4uZiJyCFpU352OH3srcg3GLpKBuKzd
LD9zoNPH027XYngeZ1cjKLgKlXCILWnUL01Di74pO2lAKz8pR2nsB2b4b4qH
2Q454Cqkzqz527WweuQdLO.
-----------end_max5_patcher-----------
</code></pre>

Mousing in the first slider in Max, you can see how the value is changed based on it's current value, not based on where the mousedown occurs. with @relativemode set to 0 (the default), the value always jumps to where the mousedown occurs.

**Comment by benbrackenc74** [comment]
This is working well here in vertical mode, however it breaks horizontal mode.

**Comment by fde31** [comment]
let me look into this.

**Comment by fde31** [comment]
I just added an overhauled and simplified version of this that should fix the horizontal mode and also play nicer with the steps and enum work for live.parameters down the road. I noticed this work was surprisingly not following the branch+pr model so I sticked to the `dev` branch for now.

@benbrackenc74 wanna give it another spin to double check?

**Comment by benbrackenc74** [comment]
This seems to be working well here. Requires live_stepsenum_support branch merge.
