### ISSUE TITLE
Multislider doesn't snap to integers in MiraWeb

### ISSUE THREAD

**Issue by evanmtp** [Cycling74/miraweb#51]
When using MiraWeb to control a multislider set to integer mode, the multislider in the browser doesn't snap to integer values - instead, it behaves like a floating point multislider, with the sliders smoothly moving across the full range. The multislider in the patch will jump to an integer when the multislider in the browser crosses that integer value.

System and Max Version:
Max 7.3.2 (6bf7de6) (64-bit Mac)
MacBook Pro 2014, OS X 10.10.3
MiraWeb 1.2.0

MiraWeb tested on the MBP via Chrome Version 55.0.2883.95 (64-bit)
as well as on a Motorola Moto G4 Plus, Android 6.0.1, Chrome 49.0.2623.91

Example Patcher Code:
<pre><code>
----------begin_max5_patcher----------
1906.3oc0ZszjiZCD9rmeEpbkspjpb7h3kgImRNu4RtlrkKgQFqcvHWRh4wt
09eO5AfAaCFOv3wygAFKgPc+ot+5Vh9G2MYZD8YLeJ3dv+BlL4G2MYhtIUCS
J98joaQOuJEw0O1zUzsawYhoyL8IvOKzs+qaySEDdJIFy.Q4I.FdGkI.3Xhf
Py9sxArCIVsgjkrjgWILSrs6h4Vy.KzWgKrU2rslaA9ZwXxx2RxRwBsD.KZj
KdIEqm5xWMIV+SZz29cn+z8iklKJGrkpwed2cpKyFnFK1P3f5Zs7mbr.Hn.R
l.mHaYKMFWNtTRFdEMOSOXmhFixihLZArC7ILPAIt1ZjABcT27fCCfbpVPXX
tT8PpUoZSpikkZZbV.U2rJtTeFGHrVC4JEkGQrLzVbacKA2JcpRIIe27a+hF
LRk3kcXidHUd4eUxMeeeV6aRhdRYyL.spZWSUOwJhqdAwwwctmxTUCQP6ECa
EwduKBShBBLaINCcf4QSb2t7EidDGuDIDLRTt.u++3EK.Eq.JHNMGSWW1bY6
0mzTZVRGKCMdV9FoOd0C29yUh4NmnOR1iDNoTOM8qskJuMR9qL7Zoo9FvS3H
Nc0CRO0UzLoOoxvW5wtlN8RbJgAt5UcOeCcUn9l6vLABGOVK4puflMsMuhHT
VxztLwgdA00O2QP8VbZsCNhqw4bLPyKihikK1bfboEkQEajjww3GIqvJ54h0
c0+J6QRZydbOKSCdZ6KwjvwVCY1NFKiPaCA5fvL6293Xzc3LvVBCMesxkDrA
mtCnUOLalBfx.oT5CRWDMZEwnOwaAttnvZtVF3JvSwhBMn1PCqEbEh6ydAXr
njynTa3SeEAycB7qELen7FtimVuU50fRvGo0Zqh8VIsRrzIohCzjTgI2hPCo
hca5tcuzcqwiUIC+j7UdjpuSxWHXzzgoyljE7b5Vm605s23oxssbexfjnGQj
TUFI.j.rQH1c+m+rhlC5GLGNGZs39.q.+NIRiUPIdWJZUCGkKCRsMwjbL2B8
z3q2vLifu8Am9ao2iDWAeAkmoHW6XKQPSJk5qE7j9mkiXsDaKyGVmgZOz6J9
R0fqRj6KHYnw+AmjmhXiG0RatW.UDn+pYXkWiAALzrCRO3HvqzxFHavrKE2C
RudMIEKykfK8Vp8zSlh1sqVyMy7dK5aT8KZQUxwRg0zz97kYXUVxMesx2KSB
EBINjyLZxy9t6y+Vs8SVVNoQh0khTMiMiAlIhjWvBiQmyd3StvljpXChqsuo
I5DGHY02+XitiwqQxcOrrtYIzd9I6ecAevI6rxr7OYDTIK7joILhjMQIDMfZ
UykSmJMViIQckQ+DYncmXvEQzOcmboRlyiPrZ6WwtrSAkl1rqpwkhWKJ5dGQ
Rl1DEEzcs2IijroiwFQkctsq2stG9x7LSuKkNihkpsK174PooEdmMe8OixHa
QBrfXVBrsp5zr2zM7UxHioMzWSOOdhdLof+DIVrQOQ0MFjONYWoQzzpU4XRB
lKZ1l.kva1xQtxxlxiJbRWJvakQbDG7.MN5q5dj04wZzdmwNaRpkfEUgPUmC
1LfrkMTtwXt1HZmnq0XCtV5DlKN1gfiX6ZkwqEnpsPgsENr1FzKo+eMvWivA
GDR.s5A.GPFEfp37Y7FabJ3cGlXxoTtesBqJfxNqaDa1AGG14Lw7cLogDbdn
y4RfN+1gNmqCzo2IigPeb7Fcz612O77HE7RPJ6qiQViSKpGmXTqIhYXifKN8
gFMTvv85fFZwaD.CG3bauxz3crJu1NZXcQ7zgcfF05ob6H5W00w6R.h.QmG.
m0SfzWmDmYqyNtirGFbQ6vn80AtRonXCfLTStR1HsEmu0XCUdu6g79d5bFN4
7Q45mIks4HnbsF6Tnbe2so36XD49p.7WTSd4o07I98eJ9yiSZUtlMc6ENxfm
66tQVI106CASCq0eUm5rudkvsCr3KvTbnW1GdZWCDtctNvs40Nse5ZfuxBqO
QLuL9q1UUqqP.yt1u3e7eL4yBR0GMXwmXA7Kv2HaJC6mii47xbfirIU0Yx+w
HOMCZ7Fkkl23jj19SuRYFzxwVn0MU+mF63zb1pRjoXGrfl5YLlKHYUmk2+Vw
HevysgDGiyNDLhIbEwXb0ADe1042JI14lQh86oDGbSIwvdJwvaBI1qmXrJU+
aDP1suhr6MCJ6zWQ9lAjs6MJeCIy8Tj8uYjX04P7QCkOASPG9e2PxL7CFN68
Az1n2rFV2NxLrmxr8HIxfudW8OmbQEnZ97ocT9oWzm4KIkFgRK9HdUeD3t9l
e6+vfie4itJkr5AUICpqWNUcbTtMMZlolC2hT6r.O7BIDZq2QRX8Jvbf0Qn6
sSkkZJVi.8wFEBKuN.cKbDKGpiJvsHzpGRXxkw3yUXe90JsMa+f4KBCCCBTk
khT8j+eH7z5n0IpFoJsLIiJmBkoW6UAd8EQ8TzbOhF89PFkBs+HljFAy6StG
GSfbL4wQqB8UZVzSoAdUjF+dHMZl3qi3zL9SKxi2qbsxXHcPcKojjCpWoCpU
oiqSo1qQoCqOI4L+y69e.0CwO7.
-----------end_max5_patcher-----------
</code></pre>

**Comment by fde31** [comment]
yeah. seems like there is no code in place to check whether settype is set to integer or float.

**Comment by benbrackenc74** [comment]
fixed and merged to dev
