### ISSUE TITLE
Mira.frame in subpatcher incorrectly opens in patching mode

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#55]
Pretty sure I saw an issue similar to this posted previously but cannot find it now.

Tested on 
macOS Sierra 10.12.3, Safari 10.0.3, Chrome 56.0.2924.87
iPad Air 2 iOS 10.2.1

Steps
1. Open the patcher pasted below
2. Open browser, point to miraweb websocket connection*

Expected: Miraweb mirrors mira.frame in [p Mira] in presentation mode because [p Mira] "View: Open in Presentation mode" flag is 1

Actual: Miraweb mirrors mira.frame in [p Mira] in patching mode

Does not seem to occur using Mira iOS app 1.2.2

* May require quitting/restarting Max and/or removing the Miraweb address from browser history to clear any Miraweb browser "Configuration>View Mode" settings

<pre><code>
----------begin_max5_patcher----------
1093.3ocqVsziaaCD9r7uBBcosANajj85cydH.4POl1BTfdY8BCJIZYlkhTk
jxO5h7eOCIkjIss1WnFvxxyLb3Ley2LjOMIJNWrmnhQ2gtGEE8zjnHqHifnt
+GEWi2WvvJqYwEh5ZBWGO0oSS1qsx+aMoQsjmbE5OaHbjdCUgZv5hMDI5Woq
QGDs+hjfjDbIkWY0OEofEgvLivCHvyMLhlT9aK4octIWJ1oHxonFAkqQZApl
Jw6H4H3qRT7HQCqiyIEZpf+gk7k7eeeC7OR4cnu0YJrDoPprK8p0RbMAQ4n6
arF7f48FIQAIE13DTsnjfxIE3VE4nUKi+GJY2ctvBVxec5RVFiVyvUHHuSMw
wWKzsX1cn2U7X.NCLYcL3rOf9F9..d+aKE.Q3oVCp+DDCZrz7JneOByK+jPB
lUK15.YxvlhKKAqUn0RQcOrhfhfVHOzWLYT.HEsbaEMMsSJuslxgBis92KrO
BWIgjyweVjdUxTzrqMOmm7YyOoWO+pDzCcqgVZYJh7u+wYwGctnU268jNoJ8
AFwZbrQvOlLw7X5qjhxI6f83LFpCeiuTVkLdVkcShISxRmayK6yrrKmUou5r
xe+HxtboKYhhWSYjsDoBnVdXdTLtowSbj2RLHv2EVGcyzAQTtSzrAQRxVZ+5
yFjhkPVqgTtU5hu8KlGezM.GTxao1PwIDpES5cXOPcqEZRyrE9Eysn17aSNh
TPYqhYZYK8.knXAzPQ49cfA4bIYMtkoWsVv0J5+YiuT.+uj903BRfu8Uxg9L
ax8UIEy5Su3JIsTvMAQv1ZD2uc2C7XGa1OYrVvwMWXw.W.fkQTBcr5VUNVZp
D4NBQeoHVKDrPUCqiQVq6T2PgIdgnnVzLtRIsZyyr1bAnr947sUiZUK2ocEz
poWovaCQaMlw558Bc+dLmVi0DM0UBxRFTR3XHQ2nJjBFKHecZ1dAMk.Itfri
Vp2X2Hex.XNsomDEOTkKoUvnxPYZbkJTxYMnfn17tlzUZBb9DjEgFDb.peGo
+Tp.4O6Apgir9Cg9ryZTLJzOhDaMyuIRxW9h+RCFgm4o3RSwGalW5M25Fy4F
hmtvNXelG6ejw4iO76Ri0i5Gs2MR4cBf0PGN0gJ9gwVrbnkeDSdKXxrrEt4a
NnwNdKcdxIXxXiwNAuxhC1LyU.z.CyQ4OKX77oeQxcR6KDPgEirKWL7j5LVe
noaxGnD9F3RSee4JrVKo4sZxw2TdEKupkoTvZIh09p806CALAu5EJaA1q1Hj
52xB5SsYinmx8G9dzlAhp+q+evdGtD3nLyjWnaMwx.RStwRDtF3olOK.Q2l8
93mo9wRNt3wJILSo70xLeCAz3CKnUvsWHELZwiAkBOL+3gwlwdcSgQOLw+JJ
czU2QxWfq9z64nC3dL4XV2ACCrum6bjiG1L4XRzcuVaZb5k6Lw0IWp6jKzc9
k4F+hbmdINXm+wjeBTBiZr.
-----------end_max5_patcher-----------
</code></pre>

**Comment by benbrackenc74** [comment]
@1offby this is over on the xebra.js repos:
https://github.com/Cycling74/xebra.js/issues/16

Closing out here as it is an issue with xebra.js, so feel free to follow up in that repository, thanks!
