### ISSUE TITLE
live.dial shows float when set to int

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#56]
mac OS Sierra 10.12.3
Max 7.3.2 x64
Mira v1.2.0
Miraweb 1.2.1
iOS 10.2.1

Live.dial set to Type int displays floating point in some situations. Also occurs in the Mira App.
Is this MiraWeb or Xebra related?

<pre><code>
----------begin_max5_patcher----------
1072.3oc6YsziihCD9bxuhHNmMBaCFXuMRyg8v73vr2F0Jxg3P6oIlHiIpmc
T+eeKaCDHaRZ5YY0lQh9P2F65kqp99JR5eLel2lhm4kdK98EecwrY+X9rY1s
LaLq94Yd6YOmlyJsh4kKNxWsUvx8V5N8HSIY648O7qnGZN+fhWxkZlVTHMBg
p2mkpAoMBmVjWnbw.Zk+xE9qhhiwjPyJebTPHZo4fEOTqoXq0YEa91uQBacC
SAQglqVykrM47ttpaHrVwS0NmgIQqhi.2fhHF+FDrBCOQnc7krZeQkNmqs2d
b8ttsze+.2YIOukK71kWv.K+Pa.oSeTHy55PbjwOn3vq4N1gCb3hHS6E+PPH
jMwPylkLH6slo0JwlJM+zpx5pWc4yTgxq3E6Z1tY+t4r7BY1sph8Dt7wBktU
52Wob01KHYSFBcgy1C2IaN0jLtzwLaaH12+hmWIE5R82cE5vKEkZ9AapH1c1
Kyme5O1e+x7kCroeuPwVsyX4WqqdCK8oLUQkba2c6zwh7tcSIhfs8H1qMjbf
tCyOTSaC9pMl9MNJSV.1JWj9TO.v+rW7M3mS8d9cxcVILMrG4px5rfM4Aotu
4vyQKsOJjtGI1GU7ihF4s3IOlBBNMDYUJWK0yz.OmpEa4JYkvdWlaJXfKsU8
y3rZ6FeW0VQwWfrZU45OxkUtrs2V9NVUtteIdS1NQ9I1mtPllFWO2o0sWdcX
p7WgSBPnXCIEAQhvT6JXQngQoI+UqCpQofvfDerQz.pgZytxP1QrrcmoF9ju
7QINO3mD6G3VAa0mZDxkxLGj.GcB2.8ZEG.LacVGTMoU9JcQlhsU.shsU3VP
hK4AXJ3zVvlWcNcOjPEM5zEK0VL97dIvHU9dl5IuwwTePj8n9V0zRdNzHAWz
dkJDNBx60YcZXhaFClfB5OYomR9jDRLxHJh5iP1rOJIlPH8UZWgrkMDFE7Nk
Y3X6oZ9yZqYWKjFjB+sZdK1MWH48BNZPT.008PiBQAtYkjfX6dzjSSTRSgLd
OcC8CSRr8fgTPgX2JBkD02yax5oVBhhP1.NNw2GYMPTRTL5rwyPEX+OuKecH
Ya65UPkCDozGWNvK243xAq18HtzBlZFHMVVq0dSvyI34D7bD.T3I.0DfZBPM
V.J7nNuCOMuaBdNAOGM.EhdK3jo2tT7W0MsH62b1nDBeoHmo.CucL9rp8L1O
C+vsPSWkeXn3gVFf2Jx+pTGC0yWl5.GQirpPBoTGRIFm3HNtIuw0U7FrFC8x
dIVig5v+m3LF3U6bNiAq1cEmwYXr+8eJ1yMHdbMHdhEXhEXhE3+TV.7HxB7K
vWz7evyOx0hT1hOwq3Suh+zq3+K.Pcfuj+E9.riabr1+d38xgUzgAuW7mOZ9
2keuN99Vt+0HGllfONSvQgIXqOPvjGry.gITSDbmPL.f3Wl+2tT.KCA
-----------end_max5_patcher-----------
</code></pre>

**Comment by benbrackenc74** [comment]
I think this is actually handled in xebra.js, liveDisplayValueMixin.js, but I'll leave it here for now.

**Comment by fde31** [comment]
OK I tackled this in the xebra.js repository on the `liveparam_intenum_support` branch. Once we resolved the monorepo #43 thingie this can be merged over I guess and tested more easily than with the current setup. Please note that the provided example also uses Steps, which is a separate ticket #60

**Comment by benbrackenc74** [comment]
@fde31 I still see numbers like 21.0% in the example above. Maybe this is handled in unit style definitions for '%'. Notice that 'custom' and 'native' unit styles aren't handled either. Maybe that is another ticket.

**Comment by starakaj** [comment]
Can repro on latest dev, which has merged `liveparam_intenum_support`. Maybe the merge caused a regression? Looking into it.

**Comment by fde31** [comment]
just talked to @starakaj taking a look

**Comment by fde31** [comment]
ok. I added custom and native unitstyle support and adjust the percent option by taking float and int type into account. should be good now when consuming the dev branch from xebra.js @benbrackenc74

**Comment by 1offby** [comment]
Thank you all!

**Comment by benbrackenc74** [comment]
working well here.
