### ISSUE TITLE
live.tab finger drag vs mouse drag

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#57]
Mira v 1.2.0
Miraweb v 1.2.1
In Max click+drag on live.tab scrolls through tab selections.
In Miraweb live.tab touch+drag not support this behavior.

<pre><code>
----------begin_max5_patcher----------
482.3ockSssbaBCD8Y3qPidlxvkX639qzICi.VvJQHwnKTxjI+6UWPwjF2lj
GrW1UR6pyE8RZBtUrBJL5mnegRRdIMIwWxUHYKOAOQV6XDkea3NwzDv03rvZ
ZXUGqOSj.Rwn8.ZfxGAIRKP8RxHZRXTP7HJ8yLvelXEtYhxYf1OgxshyDc2E
aaZjPmNbCKOUmeHCc997hLTUw4PHu.8v1Yn899JZe7G2sq4BiN18BWwWSSc+
k8EgLit.4ZRariKDImLA2bM6zZXTNnZh2+8XJbQzOOCA.YYfvuAlfXA4CeWB
4PgiCJu6riWpNV9AFY28QBJqvQzTA2yDejypvuMJoEfZP1.bRaPsJuIeVGEU
xBz2PzZIs0ngqeo1H1Ml0wdLCHFhki02OTlfO9uX32sQ0EgT+k1YjyqtwZfE
Ra5gfCN4P+agObQB97AgQ5i1I3hJ5pO.K.28APGubU9dWyMbp9MGeQXcu+KF
9llwIpjjO35dTrnibg0RvncO8W5zUOTw+wCUeNur9T8wLzgvKp6qxOUcvFbd
oxcloVR2SiRgg2ueP6LPke9iNeyvj44EPp1rhdfZg4iBoK8TlOkxCodKFVBK
z398hHlHsPQawgQFz+0igG83IQOH4Fp+Vl5l7qo+AnDs5fB
-----------end_max5_patcher-----------
</code></pre>

**Comment by benbrackenc74** [comment]
fixed and merged to dev.
