### ISSUE TITLE
live.* UI objects do not use steps attribute

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#60]
Found while looking at #56 , none of the live.* UI objects pay attention to the steps attribute.

<pre><code>
----------begin_max5_patcher----------
1150.3oc6Z0zaihCF9bxuhHNmMBaCFXtMRyg8vL6dX1aiphbHNodJwDYLQc1
Q8+95O.BNhPncopsRzCIFa+Z+9wyyiMQ82ym4sI+QZg2hOs3GKlM62ymMyzk
tiYUOOy6.4wzLRgYZdYrSzU7xC5YszN9IhfSNPu1vpmxKkYToYAfU8djHSum
w2uVPSkVG.BRV4ubAL.q+BY9DDtxewcU1v1Z1i7M+7OBpWc6RK+0QpcQ77Vt
vaWVNQsn20rWBk+Ioh0TNYSlYlfydGiW6b0cVPNQ2tlHkB1lRI8bqhpLSUpQ
G6Ykz7c0cW2e68LKmuum7iybKtOWHG5jqCZ+NFqjyjExekc0ITHoGMQSrcrm
lO+7WlOeZ9xmClnHiskJtJlvc3AiI.XjEF.LXBC.I4JXBzGYLgS94VXhqO42
WXhsLR1UQD5A+A3tmuLALx.IhC0eEDrBFZUKNWaEzBJWRjrbd6RXarRX89RN
djpx.7TGHv+WHDIUphQcHllmkKp.yZG1eUTbLDEpa4CiBBAK0Czoy2NpQQqh
iTVAhPWKteKvstUwd.teoTXKH8fZAcL1AULYPD5xcWCSLvPnu+paB5CekA8G
XBxpc5UtaTckC5sgj9vdQdIea6JUWxeHnAqaBNUJPUs0+g0ve3yCwC75GfMz
sxAjUGPr87b0RkwRevr8sxcFC0rrSTQQk6YRdpT2OsLinklGYb6iHyiB5IV8
7s8PDpziT4vkBKj5Qr8Z.dGxUxg7RV0dqJXpszT0u3tMMnwOWtkk+cURnrX8
2n7RaxwaKcGoLS5Vh2reGK6LOtMkoF35YGsBd40hy6uBlD..wZ5NBfhfXSKU
iPMYtNsVYCn1nfvfDendpAXsHgokV1.YzMtvL348xGjX2A+jX+.aKUWthLpb
IeukR.iNyaTPi7iJNaUVWYZRy7Kk46EjsLExwLlCIwl7TbJ0nMjMupb5AUBk
UaSatTSw3uOvUJREegHdvabVpux1euruZpgqkw3TmRENHJ.ay03nPPfUiFED
a5CmzPBHooJ+yw1P+vjDSEKDqLH11BgQQt56zL5gWpsCAI1TktBXbf.DW3XB
.C..8jiS78AFWMJIJFzoYvmsYiEbrJO4Dx9nDTrwI.Xe.vD7fjXDB4lbKTUl
T8l4XM.FonhUDQbXh8.bHRCNbKMNlMvH2aWNu4HR0sL9rPeiolQkzGs.k0Lt
V9jN3XZL4kFxT84Gi0p0rdSzyI54D8bDHTvIB0DgZhPMVDJ3nddGb57tI54D
8bzHT.bezIcXTv9WZ8ug7n4BeOOiHTK71w3cUcVrWh9.LBGYJknPL1xhhgIV
0gdEGttg2RZXXV9lILLPx0kBCC1rWSgggxQ6VXnuyJ5QXXnpQMT+WrgWpYby
vc7IrsdqyQaAgi6BBmTAlTAlTAdUUAfinJvzOz7zM6+Hdy9+jlchJYojE+Es
j9t4J9t7paeI+NdWkw0OV6+BtWde4pawtmNT9hCkAgIPyd.TrBncABSvZO3c
wgxpV3OnmJ2qlvh+4d8+3EuEmfqr4o4+GZxKOnA
-----------end_max5_patcher-----------
</code></pre>

This attr will need to be exported from xebra.js first, then implemented in each object.

**Comment by benbrackenc74** [comment]
I've implemented this on the bb_livedial branch just for live.dial. There is a not insignificant amount of work to do for live.* objects.

**Comment by fde31** [comment]
potentially something that could be handled more generally in xebra.js!? Not sure

**Comment by fde31** [comment]
Ok I made a few changes in xebra.js for this one and also adjusted the way live.dial and live.numbox pointer interactions are handled. This way steps and enums (as outlined in #61) should now work smoothly. The xebra.js branch is `iveparam_intenum_support` while the miraweb stuff is on ` fde/live_stepsenum_support`.

live.slider is left wrt horizontal. Didn't mean to interfere with the work @starakaj is doing right now. So letting him comment on that first.

**Comment by starakaj** [comment]
Ok, excited to see this working!

**Comment by starakaj** [comment]
On the xebra.js end this is working flawlessly, and definitely uses steps correctly. I think we have to make some changes to miraweb itself, however, to get this to work the way that it does in Max. On the desktop Max end, it seems like changing the number of steps actually causes the object to enter "pseudorelative" mode (hopefully if you play around with a live.slider object you'll see what I mean) which I think requires that the miraweb implementation of the object takes into account the steps parameter. Anyway, I'm on it.

**Comment by starakaj** [comment]
Cool, so in conjunction with the `liveparam_intenum_support` on xebra.js, this should be a decent implementation of how things work in Max. Basically, integers should "step" in the same way that enums do, sliders in relative mode should behave like sliders in relative mode in Max, and sliders in absolute mode should behave in the same "pseudorelative" way that they do in native Max.

**Comment by benbrackenc74** [comment]
This looks good when using xebra.js branch `liveparam_intenum_support` and miraweb branch `fde/live_stepsenum_support` Do we need to make a few PRs and get these into their respective  dev branches?

**Comment by starakaj** [comment]
Indeed! I have made the pull requests, if you want to merge.

**Comment by benbrackenc74** [comment]
thanks, Sam! merged.
