### ISSUE TITLE
live.* UI objects: do not handle enum parameters

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#61]
as the title says:

<pre><code>
----------begin_max5_patcher----------
1015.3oc6XsziaaCD9r8uBAc10fjRhRr2BPOjCIoGRuETXPKS6kYkoLnnL1z
f8+dGRJIas0OztUEKJf1CxCImW9alugx6OmOKbc4ShpvfeM3aAyl8y4yl41x
twrl0yB2yeJufW4TKrPdTrTUu2p0B+4G4ZEeu3ZGWVaJDFyONH7wILbQP31h
RtIL3Oaz4.2j+fTsakVja7pQHoKQKBvQI1OhntEfbmMPTjJvyt7B2robiKMJ
W+8egE14bMjdFgdkPwWWHNWevI97y4ERytU7ihMq3FiVtt1HNIU0fLMPi86d
Qsnba61s6edPKJU6tA9zS2pGJ0lgpbKjRtvYBvrF3law601G41Ga5P8dFTqj
lJyO7nCxe9yyme5C2ymmuXf8I6kZ9xsVu2VFj6TkP4sPl+34UfKT5wQDa0lw
rOILxxjTbbDEjQYWqA.05NsnRnLbirTckFCb3Ez8eFdLB4heBz5Y+ChONibV
7WyyebmtrVs45cTnyfNmgg7CGNJzUMomC6.j66kZ6xzEtkRkeYjaoVbT1pue
GtFfLCjv0ZemxSz3PuokaDZUszkQys0KHjt55KX4cMYendir7q.HTWs5yPai
GbB2H1xqKL8qvq2sUVTjWV3SuyIBsMig9Sa5vB6z8aAnkDVLFms.jhvQoDpS
BDRR.nsqqzaCt0n3jXFhXUMlRRiSbRYjnjHqD5ElQNEKDl4i.hkgh8RvVXHV
maFWsy2zSRs06lcOnKO.TwFTGLk0oesobmluQBcNm3JsbDO3AzJ3zN5TXClt
G.TYqMmSk5JF+9dELmo5235GCGGW8I4tGL2pl53eERknWohFmFS8XMMMA6fO
DIJNysGk0QB344P90y1DTBi4pXITvfLuTDMJsGzGJJD6eq1NjNwtpzUZFGXC
R+1QFlhwXqxYLDB6R0TVZF9hlQd0lMVsiM3z1RU28IvcAePK4Emt1sBJA4Vu
1CYvjTfy0v3nINoTfwY6B5WC5Y1.+J1uJfhXQYNivTDF6pGXVVTTTeiLhm7M
JqjJ63SwfcvXxKcjo16OFKu04uI54D8bhdNBDJxDgZhPMQnFKBEYTuuiLce2
D8bhdNZDJL8VzIKfWI+ql7CSGsT3qkEbM33MiwuUsmydKyGHozTWENJgR8rn
LByOc3lCGttg2azvvr7cavv.6je4fgAa1HOX3xT+aM1+FT+WMK90Z3aZPyUm
YbWGL9D1y9UmilCIiqCISSAllBLME3+zo.jQbJvz+n4o2r+za1+QQwQgQlyC
9hnVL8J9+K4U2+k7uvupZbyiUn2v6keKr5dr6oKkewkx3DFwECLvQHdGjvn1
L3ciYG7GOHU2id++9KvAI56xM3fMOO+uAy8t9tB
-----------end_max5_patcher-----------
</code></pre>

**Comment by 1offby** [comment]
Here's an example where live.dial shows NaN in the Miraweb browser:

<pre><code>
----------begin_max5_patcher----------
1069.3oc6X0zbahCF9r8uBOb1qGIAHP6sNSOrG1s6gr25zwiLV1QMXIOBgmj
sS9uu5C.iRscH6PZOTxAhPRuevy6yyq.+s4yh1HejUEs32W74Eyl8s4yl4lx
Nwrl6mEcf9XQIsxssnR9I1psbZYzR+pmnJA8.KbwOG+k10OR0E2yE6WqXEZe
jfIfUfkKHo1q9ww3UfEeowDQ8AYstjocgD05HEqhIzTMWJryCalmu0Ea4lu9
aHBrMrziGYTEUTv5u2iloNvzL0ZlftoLbsd9uexFmrBiwYI4KW.AtjECryjP
vuHu8Is9oiLuoQQKWDsqTRMtp2yFWz9n0FZZg1fbVfqPVJUMA1FJvpr7bTbp
cD.kkjBWZWnycUTicqoZshuoVyNOppoF1TDs0oxZlbW6zsy2GSJkh8WnVl1V
KC1b08Rkta228jn3R6pELPWXMlAKZ.pOIsPEDaulaujXuf5fs.6pEbck9Ie0
C3W+44yO+O20mmubfT5CbEc0Nq2aIOanEOrWIqEaCIOeGSNNyVjP9qoFtf8O
Cs.litJeFLb9bGa9JbygEd9dgzXSIu3g9wIfIB5gaNCsBnSLUUSx4.NCr8UO
6Lao6Vtvear6VE6Duc+9YnJCfoMoasxSSdDmD4MUtkoD0bWBM2VrLgzUTeQ2
nNF1Gp2xk2Yff5p0+kg53glnsrcz5RcX4cy9c7xyZo9xfVBYje0F5UTOcGXE
hj.g4VIWLLNCgciLCRMxPXGkzaCr0njzDB.Y2ZB1JTcirR2Xm18ElgNGK.j3
i.fjCR7iLSEJzMXoXumwixrMgZl8nRdznCaPciojt8Wqk6UzsbCu4rPoUf3A
OilxrZmVJpASOX.TdqM80QcEi+9fvzko5iT0CQiiq9S99602plFTg.wj3bnE
qfX.D5vOHIONNNr8nl8n1Y3ZtvxlYuUG3z7kbAKH73jrDruBiyRgI9tywI4t
4vjNy2IEc8HMs49fxdvY2pzhBClE34TPJg3XQoXi6x8ihwwYg4Eqjc3+qsCQ
czwbth.Yfj1PIBAhgPGnmS..nKUyHY4vKZF5Ma1XIQZOa0.xEV6Bd1gnLiRu
QmiSI9ynQwVVPHJGX1q9PLl5RmXp8ziwxac9aRdNIOmjmiffBMInlDTSBpwR
PgF0y6PSm2MIOmjmilfx9i6bc4jkYVw+2FlIDOZovcxRpx33siw2pF3r2P+g
ARYtd+gg5fK2e.kgyblDmhwdcRNh36NPtk7+5F9Zh+gYY2y6asO3OsdFCLAe
YOiAa1OjdF257hazy3UeHFeAauu5bzbHZbcHZpKvTWfot.uqcAPiXWfeI9gl
+CV4IllWPW7IVMa5U7mdE+2qWwOTW85uj+E97ywMOVCFm2K2LB+dej7sZNLb
48h+4dtHZ5D7eDmfCSIHWLfFkHx6fTB1lA+JeBtwlmm+eDTNHF.
-----------end_max5_patcher-----------
</code></pre>

**Comment by fde31** [comment]
Similar to #56 this is tackled in the xebra.js repository on the `liveparam_intenum_support branch`. Once we resolved the monorepo #43 thingie this can be merged over I guess and tested more easily than with the current setup.

**Comment by fde31** [comment]
@benbrackenc74 if you wanna test this please get in touch as there is also a change in the Max backend to make the transition of switching back and forth between types (INT, FLOAT, ENUM) work properly

**Comment by benbrackenc74** [comment]
working well here, and tested with changes in Max.
