### ISSUE TITLE
Number boxes always behave as floating point

### ISSUE THREAD

**Issue by evanmtp** [Cycling74/miraweb#66]
Somewhat similar to issue #51 re: multislider. When using MiraWeb to control an integer number box, the number box in the browser doesn't snap to integer values - instead, it behaves like a floating point number box, with digits after the decimal point. The number box in the patch will jump to an integer when the number box in the browser crosses that integer value.

The issue occurs when testing on an Android phone (a Motorola Moto G4 Plus, Android 6.0.1, Chrome 49.0.2623.91). When testing with a MacBook Pro using Chrome Version 55.0.2883.95 (64-bit), the integer number box behaves correctly.

System and Max Version:
Max 7.3.2 (6bf7de6) (64-bit Mac)
MacBook Pro 2014, OS X 10.10.3
MiraWeb 1.2.0

**Comment by fde31** [comment]
afaict number needs to be enhanced as there is no proper support for the _format_ and _numdecimalplaces_ attributes

**Comment by benbrackenc74** [comment]
numdecimalplaces is implemented for flonumber, but not number, so there is so inconsistency between these two implementations. `format` is not implemented in either. Maybe we should collapse these two, use the format, and create an alias for number/flonumber.

**Comment by fde31** [comment]
I agree that we should consolidate the two objects here, use the Factory approach (I guess that is what u refer to with 'alias') to get the right UIObject implementation to deliver the number for both flonum and number and just use the attributes in a consistent way.

**Comment by starakaj** [comment]
Ben --- want to take a look at this one?

**Comment by benbrackenc74** [comment]
this looks great here, thanks @starakaj !
