### ISSUE TITLE
@ignoreclick attribute is ignored 

### ISSUE THREAD

**Issue by matcham** [Cycling74/miraweb#67]
when an object has it's ignoreclick attribute enabled, clicking / touching it in miraweb (Safari / Chrome, ...) 'capture' the cursor, and the object placed in the background don't receive the touch input.

This DO works as expected in the Mira iOS app. (and of course in Max) : click & touch pass thru objects with @ignoreclick 1

example : 

<pre><code>
----------begin_max5_patcher----------
482.3ocsTsraaCCD7rzWAAuzKpFlx0V18T9ORKLnj1HwDIRAxkFNHH+6kODS
rKTSbKPuPJNb4t6LCodIOiVqNCFJ46j6IYYujmkEf7.Yyqyni7yMCbSHLZiZ
bDjHsHtGBmw.N1KLjZKhJIw80chNoRCMChlmHreH4xVhoWYGZkeAIM7IzpAB
prM8fg3NC1CDyfnEzoTOHjPixJC4e6LXsstd.7HrYDocTYwA.C825YzIN1zK
jcGc8.F4Gqpb05BB6aGBSrvT09UqI+b9Ph1.UT0O9UFK0FF74XAoz2qnPlJH
yi8Zdten3F0vnLQWj.r+LANrIz3a2sZaAY2V+B+3aseLK3ySPLdZMW1QWhcG
R09BW5xh+efyW6sm3ZIeDVXmaVMphpAqzqFGphRylORNVTJdymm3ZWGgf9HH
4+1crOSORgwOAsG4HpENKFd+KyrvLqLd9OXA0CI3D9kcwfR1srFcUXtGUZ7F
hKoCaVXOg7jvHRbNtevdSS+kd8nPyW8fO6I4pl27Tm18Xt8e5o6lf8FM4R28
euWuub4Wtkexc6qbt0WvtPxn7ooSf1HbuO8DzSOG4dTo8KqJBKEx3xfVR0fW
8hwWFP3ZGAPW269GWnuNueGMdTkydjVwrP6p7q4+BbRRXMM
-----------end_max5_patcher-----------
</code></pre>

**Comment by benbrackenc74** [comment]
@matcham I can't reproduce the issue you describe. When I try to repro here, functionality is exactly the same in Max and in the browser. Could you send along a demo video of it in action? Also, your Max Support info and browser versions?

**Comment by matcham** [comment]
Ups, sorry for the noise, it works fine now ! 
(this problem has been fixed in latest miraweb version)
I updated my miraweb just before reporting this issue, but I didn't refreshed the web page in my browser (safari / iPad) ; so I guess that an outdated version was still running on the iPad...
I close both issues
thanks Ben
