### ISSUE TITLE
The comment UI object captures touch & click

### ISSUE THREAD

**Issue by matcham** [Cycling74/miraweb#68]
this problem is probably link to this issu :   #67 (ignoreclick attribute is ignored)

The comment UI object (which do not have ignoreclick attribute, but which by nature is not touchable...) has the same problem : it captures touch & clicks, and prevent objects place in its background to be touched : 
place a comment object in front of a slider : the slider cannot be controlled.

(this works as expected in Mira.app and in Max)

<pre><code>
----------begin_max5_patcher----------
416.3ockSsraiCCC7r8WgftzKYKhSZaR2ekEEAx1rIrUVxPhxHEA4eu5YSxB
u.YuHZMjhjyP5S0U7V8QvxY+l8GVU0o5ppHT.nJeuhOHN1IE1XX7N8v.nH9h
jOBNRQb5.ZYYmL6AsS1qdfXiFXJfPZW2ATsmoUL5.vrRrGLkrHQEzocpXpVm
AUtAsij.EK7xL5nfhIZmA5nTiucyiKWvZd9kjoIXdxiwdK+FrO1h51O9USSo
lV5KIDw4WJHpJ0qIfcttNbr3N0laI0jvnDCvLdtkYM+als44qY1qKCl.+9gY
ozPeMBoGv4yRZ9Okv36HBL6.knMQ+l6TOJgIlf9cBhLXqifKeYyBSVYB7W5.
86E3B90cgTq1OuFcSX90ICcGwUzg0y3CUSnEKbN4ONdKl+yY8.ZDO9dH6E4p
Uz84dieKt+Z85t2hWG2heMdtJOw2tZ9s3UkZh6UZeJjX2m+UQuL4VdE6hIiK
FGm.iE0pHACzyStOzlv0MKhWQU5ZTK49+hwR7qhHBim.ju6clzX431W3omp8
iGkCyBsuxmq+Fj0TUnG
-----------end_max5_patcher-----------
</code></pre>

**Comment by benbrackenc74** [comment]
@matcham as mentioned on #67 , I can't repro here. Maybe an issue with different browsers/versions of the package?

**Comment by matcham** [comment]
fixed in miraweb 1.2.1 .
sorry for the noise...
