### ISSUE TITLE
mira.frame focus message doesn't work

### ISSUE THREAD

**Issue by matcham** [Cycling74/miraweb#69]
open mira.frame.maxhelp
in 'scripting' tab, click on 
"script send scriptyFrame focus"
nothing happens in miraweb (iPad / Safari)

(it works as expected in mira.app)

**Comment by benbrackenc74** [comment]
i can confirm that this has yet to be implemented.

**Comment by benbrackenc74** [comment]
workaround for the time being is to manage tab order by using the @taborder attribute.

**Comment by fde31** [comment]
@benbrackenc74 I added support for this and tweaked the taborder a bit to match the Mira App ordering wrt <none> values set. 

@starakaj I figured the `mira_focus` attribute is used to make this happen. Weirdly enough it is part of the state tree already (although it's not in the supported_objects list/attrs). To make things a bit more misleading: if I add it to the object list of xebra.js things start acting weird, as in no frame present. Does that make sense to you?

**Comment by fde31** [comment]
ah. there is a weird thing with this and I need @starakaj help here. I can make it work in a weird scenario:

1) add `mira_focus` to the `mira.frame` attr list in xebra.js
2) -> doesn't work when reloading MiraWeb and sending script mssg
3) Follow up connections show no mira.frame instances and addParam fails for a few nodes (I assume it thinks there should be additional nodes in the tree, but they aren't), as a result MW doesn't show any tabs/frames
3) remove `mira_focus` attr, rebuild xebra.js and reload MiraWeb
4) now everything renders fine and sending scripted focus messages works seemless.

So yeah, I wasn't 100% aware of this as my tests all worked (once I removed the attr again and didn't restart Max). So I'd pass this on to @starakaj and see if he has additional insight wrt the xebra state when adding the attr.

**Comment by starakaj** [comment]
Ok, let's take a look...

**Comment by starakaj** [comment]
Okay, fixing this actually required pushing a change to mira.frame. Seems the focus message was changing length depending on whether or not the particular mira tab wanted focus. So when a tab wanted focus, it would send the message "mira_focus 1". But the default state of the parameter was "mira_focus" without and attached value, which was confusing the websocket layer. So, I just made the default state of mira_focus 0, so that then length of the attribute doesn't change.

Anyway, testing this will require rebuilding mira.frame.

**Comment by starakaj** [comment]
Quick note, this will also require pulling the latest xebra.js/dev, which adds the mira_focus attribute to mira.frame

**Comment by benbrackenc74** [comment]
This is working great here, I'll merge this PR.
