### ISSUE TITLE
Number box should support non-decimal display formats

### ISSUE THREAD

**Issue by starakaj** [Cycling74/miraweb#70]

**Comment by benbrackenc74** [comment]
@starakaj do you want to check this out? Thanks!

**Comment by starakaj** [comment]
Yus!

**Comment by starakaj** [comment]
K, so this is broken for negative numbers, for some of the more esoteric display formats. I'm going to take a quick look at the number object in Max itself, see if we can move code over without doing too much extra work.

**Comment by starakaj** [comment]
Ben and I looked at this, and it's not really clear how we could handle large negative numbers coming from 64 bit Max. But it's not clear that this is something that we should be worried about. If the current implementation seems more or less okay, then I'd say we can close out this ticket.
