### ISSUE TITLE
mira.status: changing client name in browser adds another connection

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#87]
When you change the client name in the browser, it adds another connection to mira.status.

To repro:
1. open miraweb launcher and connect to a browser
2. open mira.status help patcher and 'getconnections' - one client name is posted in the Max console
3. in the browser, click on the 'gear' icon in the upper right and change the client ID name
4. back in Max, click on 'getconnections' again - two client names are posted in the Max window

**Comment by starakaj** [comment]
oh yuck

**Comment by benbrackenc74** [comment]
Slight addendum here, in the client, you need to disconnect, then reconnect, then query mira.status again and you will see a second instance of the client.

**Comment by starakaj** [comment]
Ooooooo can repro. FWIW, this appears to be a regression, as I can't get this to happen with the previous miraweb release.

**Comment by starakaj** [comment]
K, should be fixed now near as I can tell. Requires rebuilding xebra-communicator, so unless you're running npm install again you'll have to cd to packages/xebra-communicator and run `npm run build` before this will work.

**Comment by benbrackenc74** [comment]
working well.
