### ISSUE TITLE
mira.frame help patcher: basic tab not showing in browser

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#88]
If the mira.frame help patcher is opened before the browser opens a connection, the 'basic' tab will not appear.

Steps to repro:
1. open mira.frame help patcher
2. open client connection on browser and connect - basic tab is missing

**Comment by benbrackenc74** [comment]
Additionally, if you connect in this fashion, the 'supported UI objects' tab is always missing a number of objects (always the same ones). See attached pic:

<img width="1424" alt="screen shot 2017-05-18 at 1 54 40 pm" src="https://cloud.githubusercontent.com/assets/13490380/26223115/95725e26-3bd1-11e7-8891-a236f3185204.png">

**Comment by starakaj** [comment]
Wouldn't be surprised if this was actually caused by #89, since an error in mira.motion might have caused the page to stop loading.

**Comment by starakaj** [comment]
Sure enough, I think this is OK now :)

**Comment by benbrackenc74** [comment]
fixed
