### ISSUE TITLE
mira.channel: freeobject errors in Max when sending lists to client

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#92]
Sending lists to the client via Max produces errors in Max, though the data gets sent:
`freeobject: 610035eba940: bad object`

Steps to repro:
1. open mira.channel help patcher
2. click on button to open example in browser
3. back in Max, click on "send a list" message box - `freeobject` error appears in Max Console

**Comment by starakaj** [comment]
Looks like it's time for another episode of "Sam has no idea how to manage memory"

**Comment by starakaj** [comment]
Yeah, that was the problem all right. Ok, bug was in mira_ws_server, actually. You'll need to rebuild that (and not mira.channel) to make this work, but it should be good.

**Comment by benbrackenc74** [comment]
fixed, nice!
