### ISSUE TITLE
umenu: popup text cut off on certain devices

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#93]
On iPhone 6, the below patcher's umenu popup is cut off when opened on the client:

<pre><code>
----------begin_max5_patcher----------
402.3ociSssaBBDD8Y3qfrOSMnRs09p8Ov1WZSiYAGwQgcI6EiFi+6cugfQS
ZIgkcNyggyrmgywQjB9QPRRdK46jnnywQQNHKPTHNhzPOVVSkNZDcCvzjTel
CTAi1.2m.W6v3E6dJOuCjoaPVMnbEZb.rkJLUPAhU.iVTCCygJnIHNxWffSR
SHo1kOY86emKut+CAzGrPSUCdmEHqrOZIf8LWhFAPR9oWmbspSnSCnR0Iu5H
jqRWUtEYUqDPoxKy77QYoIimmYeLetccxjQYWKsutpSsPnsPlxp.28UVR5AX
8JpRIvBsB52ICFSvYrFPsF3a5f6vGdrVyYUOzjtgkbKWn9aZcJe5CxgrCnD6
rPe9Kww8ObqWhS+mSZMnfNZis5OXpZR1Cmpx5XVw3FWoFK2Obf5VmsibAsbe
kfqYqucv7N2c5LqglO1YqOaBrWyL98qNOdPO5rRBss8.HjHm4ZSaSZZwcbgM
7kTWHx7gtSTh.rmgd94NDpvnBkQBZg2aNNy+CEoguFDLMFNtMe4Kw+h8OsNp
-----------end_max5_patcher-----------
</code></pre>

![img_0410](https://cloud.githubusercontent.com/assets/13490380/26224711/7e792590-3bd8-11e7-80fc-7544dfaf44d9.PNG)

**Comment by starakaj** [comment]
I have an iPhone 6. Can test.

**Comment by starakaj** [comment]
Ya ok, word. Should be good now.

**Comment by benbrackenc74** [comment]
A slightly different problem:
<img width="1058" alt="screen shot 2017-05-19 at 12 09 08 pm" src="https://cloud.githubusercontent.com/assets/13490380/26263068/0126694a-3c8c-11e7-897f-b5276bf6757d.png">
<pre><code>
----------begin_max5_patcher----------
402.3ociRssaBCCC841uhp7bGpbcvdk8Gv1KaZBkVLfg1jpboBDh+80jzrzs
AZqR0M9XG65iOWhiH47Sfjj7Tx6IQQWhihrPFfnN+HRE8TQIUZSinq.llj5h
zPELZE76.R04RGrGgoq3ZUInrkYbGZMUUrGY6VKfBk62Xzz4CxRSlMzXWrvX
GMZPVxGcWA2XqKO+vCSl3qtqzpy0fqHDjoHolt29FtpBp5FVxaffahlZLuxB
melK+57KBH3rTSU8tyRjUD7VAXHyUHnfPaqohVRRAh0.il63kgAZAYdVwCJo
Mvl0TkRf4ZEDNI6VLcaFyBnTC7sdXOd+dVxY6t4R5aYI2yEp+NMOCO9FwPVC
JQ+74heMNN7wZuFm9OUZUnfNXqo59sLtiwaEJkXwwevg8jVY2WZMLyJpF6DU
SmMHy7LKMY376nvFk46cNs33NAWy1b20WVugzVLBsttADRjyryoYJamwCbgw
8wTqKxbtVJkH.CI5xehEgJZGCU6LnEtkyoYNYOohuADLM1w2sc9Z7mPDMuN2
-----------end_max5_patcher-----------
</code></pre>

**Comment by benbrackenc74** [comment]
All fixed up!
