### ISSUE TITLE
POSIX Error 7007

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#98]
This popped up in the Mira App when connected via USB.
I'm sure I was quitting & restarting Max and all kinds of things.
Don't know whether this is the proper place to report, putting it here nonetheless.
![mira app what is this](https://user-images.githubusercontent.com/1762758/28285950-6cc9158e-6aeb-11e7-9dd4-50f4b92a0919.jpg)

**Comment by benbrackenc74** [comment]
@1offby yeah, this is strictly for Miraweb dev/bugs/FRs. I believe this is a known issue for Mira app under certain circumstances and is tracked internally.
